#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other /bin/sh around, it might work, but
#       may cause problems.
#
#   (2) The slightest modification of this script may cause it to stop working, so
#       be very careful.
#
#   (3) If you are not using the official Gradle distribution then check if you have
#       all the dependencies and internal protocols correct.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Disassociate from any parent shell if possible
if [ "$$" != "1" ] ; then
    exec bash "${SCRIPT_DIR}/gradlew" "$@"
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the last option that takes a positional argument, if any
#   * "-classpath" and "-cp" only if there is a class defined
#   * "-splash" (only in Java 6 and later)
#   * everything else

# Which Java executable should we use?
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" && ! "$nonstop" ; then
    case $( ulimit -S -n ) in #(
      'unlimited'|*[![:digit:]]*) :;;
      *) ulimit -S -n 262144 ;;
    esac
fi

# Collect all arguments for the java command, in the right order to later find them
# when converting to actual command line arguments:
#   * args from the last option that takes a positional argument, if any
#   * "-classpath" and "-cp" only if there is a class defined
#   * "-splash" (only in Java 6 and later)
#   * everything else

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the last option that takes a positional argument, if any
#   * "-classpath" and "-cp" only if there is a class defined
#   * "-splash" (only in Java 6 and later)
#   * everything else

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --windows "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false;;
            esac
        then
            arg=$( cygpath --windows "$arg" )
        fi
        printf '%s\n' "$arg"
    done | tr '\n' ' ' | tr -d '\r\n'
    echo " "

fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the last option that takes a positional argument, if any
#   * "-classpath" and "-cp" only if there is a class defined
#   * "-splash" (only in Java 6 and later)
#   * everything else

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the last option that takes a positional argument, if any
#   * "-classpath" and "-cp" only if there is a class defined
#   * "-splash" (only in Java 6 and later)
#   * everything else

exec "$JAVACMD" \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    "$@"
